default_index:
    path: /
    defaults: { _controller:"AppBundle:Default:index"}
    methods: GET

default_pruebas:
    path: /pruebas
    defaults: { _controller:"AppBundle:Default:pruebas"}
    methods: GET

default_pruebas_json:
    path: /pruebas/json
    defaults: { _controller:"AppBundle:Default:pruebasjson"}
    methods: GET

default_login:
    path: /login
    defaults: { _controller:"AppBundle:Default:login"}
    methods: POST

default_pruebas_token:
    path: /pruebas/token
    defaults: { _controller:"AppBundle:Default:pruebastoken"}
    methods: POST
