task_new:
    path: /new
    defaults: { _controller:"AppBundle:Task:new"}
    methods: POST

task_edit:
    path: /edit/{id}
    defaults: { _controller:"AppBundle:Task:edit", id:null}
    methods: POST

task_list:
    path: /list
    defaults: { _controller:"AppBundle:Task:list", id:null}
    methods: POST

task_detail:
    path: /detail/{id}
    defaults: { _controller:"AppBundle:Task:detail", id:null}
    methods: POST
